/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    C: typeof import('./src/components/C.vue')['default']
    ChartBar: typeof import('./src/components/ChartBar.vue')['default']
    ChartLine: typeof import('./src/components/ChartLine.vue')['default']
    Charts: typeof import('./src/components/charts.vue')['default']
    copy: typeof import('./src/components/SlideTime copy.vue')['default']
    DarkmodeButton: typeof import('./src/components/DarkmodeButton.vue')['default']
    DarkModeButton: typeof import('./src/components/DarkModeButton.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCopy: typeof import('./src/components/IconCopy.vue')['default']
    IconCpoy: typeof import('./src/components/IconCpoy.vue')['default']
    SlideTime: typeof import('./src/components/SlideTime.vue')['default']
  }
}
